services:
  sqlserver:
    image: mcr.microsoft.com/mssql/server:2025-latest
    container_name: helpdesk-sqlserver

    environment:
      ACCEPT_EULA: "Y"
      MSSQL_SA_PASSWORD: ${MSSQL_SA_PASSWORD}

    ports:
      - "1433:1433"

    volumes:
      - sqlserver_data:/var/opt/mssql

    restart: unless-stopped

  mailpit:
    image: axllent/mailpit:latest
    container_name: helpdesk-mailpit

    ports:
      - "1025:1025"
      - "8025:8025"

    restart: unless-stopped

volumes:
  sqlserver_data:
